#!/usr/bin/env python3
"""
This script is for quickly testing path planning
"""

import rospy
import sys

from five_dof.moveit import MoveItTest


if __name__ == "__main__":
    args = rospy.myargv(argv=sys.argv)
    rospy.init_node("test_moveit", anonymous=True, log_level=rospy.DEBUG)

    if len(args) == 2 and args[1] == "true":
        set_goal_orientation = True
    else:
        set_goal_orientation = False

    MOVEITTEST = MoveItTest(set_goal_orientation=set_goal_orientation)
    MOVEITTEST.run()
